---
- name: Conditional package installation
  hosts: web
  become: true

  tasks:
    - name: Install httpd on RedHat systems
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install apache2 on Debian systems
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "Debian"
