---
- name: File and Directory Management
  hosts: local
  become: yes
  vars:
    app_name: "myapp"
    app_version: "1.2.3"
    app_user: "appuser"
    base_dir: "/opt/{{ app_name }}"
    
  tasks:
    - name: Create application user
      user:
        name: "{{ app_user }}"
        system: yes
        shell: /bin/bash
        home: "{{ base_dir }}"
        create_home: no
    
    - name: Create main application directory structure
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'
      loop:
        - "{{ base_dir }}"
        - "{{ base_dir }}/bin"
        - "{{ base_dir }}/config"
        - "{{ base_dir }}/data"
        - "{{ base_dir }}/logs"
        - "{{ base_dir }}/backup"
        - "{{ base_dir }}/tmp"
    
    - name: Set specific permissions for sensitive directories
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: "{{ base_dir }}/config", mode: '0750' }
        - { path: "{{ base_dir }}/data", mode: '0750' }
        - { path: "{{ base_dir }}/logs", mode: '0755' }
        - { path: "{{ base_dir }}/tmp", mode: '0777' }
    
    - name: Create static configuration files
      copy:
        content: |
          # {{ app_name }} Configuration File
          # Generated by Ansible on {{ ansible_date_time.iso8601 }}
          
          APP_NAME={{ app_name }}
          APP_VERSION={{ app_version }}
          APP_USER={{ app_user }}
          BASE_DIR={{ base_dir }}
          
          # Database settings
          DB_HOST=localhost
          DB_PORT=5432
          DB_NAME={{ app_name }}_db
          
          # Logging
          LOG_LEVEL=INFO
          LOG_FILE={{ base_dir }}/logs/app.log
        dest: "{{ base_dir }}/config/app.conf"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0640'
    
    - name: Create a simple startup script
      copy:
        content: |
          #!/bin/bash
          # {{ app_name }} Startup Script
          # Generated by Ansible
          
          APP_DIR="{{ base_dir }}"
          CONFIG_FILE="$APP_DIR/config/app.conf"
          LOG_FILE="$APP_DIR/logs/startup.log"
          
          echo "Starting {{ app_name }} at $(date)" >> "$LOG_FILE"
          echo "Configuration loaded from: $CONFIG_FILE" >> "$LOG_FILE"
          echo "Application started successfully" >> "$LOG_FILE"
        dest: "{{ base_dir }}/bin/start.sh"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'
    
    - name: Create log rotation configuration
      copy:
        content: |
          {{ base_dir }}/logs/*.log {
              daily
              rotate 7
              compress
              delaycompress
              missingok
              notifempty
              create 644 {{ app_user }} {{ app_user }}
          }
        dest: /etc/logrotate.d/{{ app_name }}
        mode: '0644'