- name: Configure MOTD using Jinja2 template
  hosts: servers
  gather_facts: yes
  become: yes
  tasks:
    - name: Generate /etc/motd from Jinja2 template
      template:
        src: templates/motd.j2
        dest: /etc/motd
